version: '2'
services:
  php:
    build: .
    volumes:
      - .:/opt/php_faktory_worker
    working_dir: /opt/php_faktory_worker
  faktory:
    image: contribsys/faktory
    ports:
      - "7419:7419"
      - "7420:7420"
